server:
  port: 8010
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://localhost:1433;DatabaseName=NSSOL_RFID
    username: sa
    password: 123
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis:
  mapper-locations: classpath*:com/frid/data/dao/*.xml
#  type-aliases-package: com.example.entity