server:
  port: 8085
spring:
  profiles: test
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=NSSOL_RFID
    username: sa
    password: 123
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.SQLServerDialect
rsa:
  key:
    pubKeyFile: D:\key\sky_boot_rsa.pub
    priKeyFile: D:\key\sky_boot_rsa
mybatis:
  mapper-locations: classpath*:dao/*.xml